[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
panic-halt = "1.0.0"

[lib]
crate-type = ["staticlib"]

[features]
default = ["LOSCFG_MEM_TASK_STAT", "LOSCFG_BASE_CORE_USE_MULTI_LIST"]
swtmr_in_isr = []
LOSCFG_MEM_TASK_STAT = []
LOSCFG_BASE_CORE_USE_MULTI_LIST = []
LOSCFG_BASE_CORE_USE_SINGLE_LIST = []