[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
semihosting = { version = "0.1", features = ["stdio", "panic-handler"] }
bitflags = "2.9.1"

[lib]
crate-type = ["staticlib"]

[features]
default = ["LOSCFG_MEM_TASK_STAT", "LOSCFG_BASE_CORE_USE_MULTI_LIST", "compat_posix", "timeslice"]
swtmr_in_isr = []
compat_posix = []
timeslice = []
debug_sched_statistics = []
LOSCFG_MEM_TASK_STAT = []
LOSCFG_BASE_CORE_USE_MULTI_LIST = []
LOSCFG_BASE_CORE_USE_SINGLE_LIST = []