[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
panic-halt = "1.0.0"

[lib]
crate-type = ["staticlib"]

[features]
# default = ["LOSCFG_MEM_TASK_STAT", "bitmap", "mem"]
default = ["bitmap", "mem"]
bitmap = []
event = []
mem = []
LOSCFG_MEM_TASK_STAT = []
